name = "Hide Among The Grass";
author = "Silence, MaxxLite";
description = "";
tooltip = "Hide Among The Grass";
tooltipOwned = "Hide Among The Grass";
overview = "Allows you to 'hide among the grass'. It basically just blocks the AI from seeing you in a performant way. Hiding in the grass is the main focus, but this mod does a lot more. It's also customisable via cba settings!";
actionName = "GitHub";
action = "https://github.com/SilenceIsFatto/HATG";
hideName = 0;
hidePicture = 0;
dlcColor[] = {1, 0, 0, 1};
logo = "\z\hatg\addons\core\logo_ca.paa"; // Logo displayed in the main menu
logoOver = "\z\hatg\addons\core\logo_over_ca.paa"; // When the mouse is over, in the main menu
picture = "\z\hatg\addons\core\logo_picture_ca.paa"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
logoSmall = "\z\hatg\addons\core\logo_ca.paa"; // Display in creative lists, next to the entities added by the mod